# Generated by Django 3.2 on 2022-11-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('email_address', models.EmailField(max_length=80)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
    ]
