# Generated by Django 3.2 on 2022-11-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={'verbose_name_plural': 'Packages'},
        ),
    ]
