# Generated by Django 3.2 on 2022-11-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='included1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='included2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='included3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='treatments1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='treatments2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='treatments3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='treatments4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='treatments5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='treatments6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='treatments7',
            field=models.TextField(blank=True, null=True),
        ),
    ]
