# Generated by Django 3.2 on 2022-11-26 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testemonials', '0002_auto_20221122_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='testemonial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testemonials.testemonial'),
        ),
    ]
